environment: NODE_ENV

tests:
  e2e:
    waitForTimeout: E2E_WAIT_FOR_TIMEOUT_VALUE
    waitForAction: E2E_WAIT_FOR_ACTION_VALUE
    proxyServer: E2E_PROXY_BYPASS
    proxyByPass: E2E_PROXY_SERVER
    outputDir: E2E_OUTPUT_DIR

services:
  idamApp:
    idamApiUrl: IDAM_API_URL
    accountsEndpoint: IDAM_TEST_SUPPORT_CREATE_ACCOUNT_ENDPOINT
    testForename: IDAM_TEST_FORENAME
    testSurname: IDAM_TEST_SURNAME
    testUserGroup: IDAM_TEST_USER_GROUP
    testLevelOfAccess: IDAM_TEST_LEVEL_OF_ACCESS
