environment: development
NODE_ENV: development

node:
  port: 3000
  baseUrl: https://localhost:3000

redis:

ssl:
  hpkp:
    maxAge: 3600
    sha256s: AbCdEf123=
    sha256sBackup: ZyXwVu456=

health:
  timeout: 5000
  deadline: 15000

service:
  name: 'divorce-respondent-frontend'

services:
  redis:
    url: redis://127.0.0.1:6379
    secret: defaultsecret
    useSSL: false
  idam:
    apiHealth: http://localhost:8001/health
    authenticationHealth: https://localhost:8000/health

paths:
  health: /health
  authenticated: /authenticated
  index: /
  protected: /protected
  end: /end
  entry: /entry

tests:
  e2e:
    waitForTimeout: 10000
    waitForAction: 10000
    proxyServer:
    proxyByPass:
    outputDir: ../../functional-output
    idamTestEmail: test@email.com
    idamTestPassword: password

features:
  idam: false
